### ISSUE TITLE
Cannot insert "space" with tagName="button"

### ISSUE THREAD

**Issue by hoc-ht** [lovasoa/react-contenteditable#169]
I'm trying to use react-contenteditable with <button> tag. But when I press SPACE, it don't insert any space to the content.

Demo here: [https://codesandbox.io/s/button-issue-680nk?fontsize=14](https://codesandbox.io/s/button-issue-680nk?fontsize=14)

Can you check it?
Thank you.

**Comment by lovasoa** [comment]
Hello, and thank you for your interest in this project. However, your issue is not related to react-contenteditable. The behavior you describe is specific to how chrome handles contenteditable buttons, and does not occur on firefox, for instance. If you think spacebar presses on contenteditable buttons should be treated differently in chrome, than you can open a chromium bug.

Example: https://codesandbox.io/s/competent-fire-wknt1

**Comment by lovasoa** [comment]
You can read more about this issue with contenteditable buttons in chrome in [this stackoverflow question](https://stackoverflow.com/questions/22104860/chrome-firing-onclick-when-space-typed-in-contenteditable-button).
