### ISSUE TITLE
dangerouslySetInnerHTML security 

### ISSUE THREAD

**Issue by polkovnikov-ph** [lovasoa/react-contenteditable#17]
Why do you think this library disallows XSS injections on a website?

**Comment by lovasoa** [comment]
This library lets you set the innerHTML yourself, it's on purpose. If your input may be unsafe, of course you have to filter it.

**Comment by polkovnikov-ph** [comment]
This is insecure. If there's an HTML string in JS that is dangerously set, it has to follow `{__html: ...}` pattern. This library doesn't even state it in documentation and will surely result in XSS in 90% of cases of its use.

Please, reopen or unpublish the library from `npm`.

**Comment by lovasoa** [comment]
This is not insecure per se. Of course, if people save HTML somewhere, and then display it somewhere else on the site, they have to sanitize it.

You are right that we could add a notice in the documentation. What do you propose?

**Comment by polkovnikov-ph** [comment]
@lovasoa JS is insecure per se, because in absence of typing there's no way to distinguish arbitrary strings and HTML strings. This issue is similar to SQL injections in PHP's: there's no way to enforce escaping by type system. PHP solved this issue by having an API that substitutes string into SQL. The same thing in DOM is `createTextNode` that is, of course, unavailable when we're using React. Yet React has another solution to this problem: it enforces HTML strings to have a dynamic type `{__html: "..."}`. This way it's explicit on caller side that the passed string contains HTML, and that it's caller's duty to validate it. I think `react-contenteditable` should follow the same guideline.

**Comment by slorber** [comment]
I think everybody is now aware that when adding unchecked html to the DOM it's a security problem. 

So what do you want exactly? That we change the API just so that it's harder to use so that the user knows for sure it's dangerous? Honnestly we could make a poll but not sure it's worth it. 

The prop is `html`so it's currently also explicit on caller side that the string contains html no? Also if the user use this lib it's likely he already displays as read-only the data somewhere, so he knows about `dangerouslySetInnerHTML` too.

I don't understand why you talk about php. Here we are on the frontend. Whatever you use on the frontend we don't care you still have to validate the html on the backend anyway, weither it's node java php haskell or whatever.
