### ISSUE TITLE
Emiting change on blur

### ISSUE THREAD

**Issue by mertkahyaoglu** [lovasoa/react-contenteditable#19]
Why do we need emitting change on blur? In my project, a save button is enabled if any of the inputs change but if the user changes nothing but just lose focus, it enables the button again.

Edit: #16 fixes the problem but 1.1.0 version is available on npm. Can we publish the 2.0.0?

**Comment by slorber** [comment]
Hi,

@mertkahyaoglu theinitial code comes from this SO question:
http://stackoverflow.com/questions/22677931/react-js-onchange-event-for-contenteditable


I don't know why @brigand did put a onBlur listener, but in my experience I don't see much value in keeping it.

My current `UncontrolledContentEditable` I use in production looks like this and does not been to emit change on blur:
https://gist.github.com/slorber/b84c6c7c2d2c3c6250c53a001b674688

**Comment by mertkahyaoglu** [comment]
@slorber Thanks for quick response. Actually #16 fixes the problem I guess, but it is not available on npm (still 1.1.0). With that PR, I can override the onBlur event by passing an empty function to prevent emiting change.

**Comment by jvalente** [comment]
Hello everyone. Here are my warm regards to everyone using contentEditable in general and contentEditable with React in particular.

Here's a question: considering that the current solution won't work on IE11 because of [this](https://github.com/facebook/react/issues/7280) and [by](https://developer.mozilla.org/en-US/docs/Web/Events/input) [definition](https://developer.mozilla.org/en-US/docs/Web/Events/keyup) _(I confess that I didn't take a look at the React `SynteticEvent` creation based on DOM events)_, what do you guys think about using `onKeyUp` instead of `onInput` [here](https://github.com/lovasoa/react-contenteditable/blob/master/src/react-contenteditable.js#L19)?.

Kind regards and thank you for your work.

**Comment by slorber** [comment]
Hmmm I've just done some test and for me it seems onInput works fine on IE, however I've been reported there might be a problem on my app on IE11 where a text paste does not trigger onInput.

I'll have to digg deeper another day

**Comment by Treora** [comment]
The original `onBlur` issue seems resolved, so closing this one. The question about `onInput` events in IE11 may be worth opening as a separate issue, if it is still relevant.
